### ISSUE TITLE
Which AKFIN query to use?

### ISSUE THREAD

**Issue by MattCallahan-NOAA** [BridgetFerriss/WGOA-Ecopath-Rpath#1]
I just pushed 4 options for catch data from AKFIN to this repo. The request we discussed (catch by year, species group, species when available, retained/discarded, and gear) had more confidential flags than I expected so I cut out some filters to aggregate more broadly. Take a look and see which you want to use, or if you want some other combo of filters.

**Comment by biadias** [comment]
Thank you Matt. We got what I needed.
